### ISSUE TITLE
PROFILE PHOTOS GROUP/USER NAME  Profile photos and group and user names are not blurred

### ISSUE THREAD

**Issue by mauriciomholiveira** [LukasLen/Privacy-Extension-For-WhatsApp-Web#88] opened 2024-08-29 19:06 UTC
PROFILE PHOTOS GROUP/USER NAME  Profile photos and group and user names are not blurred

![image](https://github.com/user-attachments/assets/0ca29648-4b1d-4a4b-9c06-df5af53adcf7)

![image](https://github.com/user-attachments/assets/9dd64b46-bb36-40f2-815e-ce907edada90)

**Comment by LukasLen** [comment] 2024-08-29 19:13
Thanks for reporting
Duplicate of #81

**Closed** 2024-08-29 19:13 UTC
