### ISSUE TITLE
Name Title Unblur

### ISSUE THREAD

**Issue by HumzaSubhani** [LukasLen/Privacy-Extension-For-WhatsApp-Web#82] opened 2024-08-26 04:37 UTC
Extension not working properly. Name Title is unblured.
 
![Screenshot (77)](https://github.com/user-attachments/assets/2d7f6898-164a-4e60-b701-ff5b56e8d616)

**Comment by HumzaSubhani** [comment] 2024-08-26 04:43
Have deleted and installed again but still not working properly.

**Comment by LukasLen** [comment] 2024-08-28 18:42
Duplicate of #81

**Closed by LukasLen** 2024-08-28 18:42 UTC
