### ISSUE TITLE
Blur whatsapp on idle

### ISSUE THREAD

**Issue by batflarrow** [LukasLen/Privacy-Extension-For-WhatsApp-Web#25] opened 2022-11-03 14:03 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I'm just frustrated with the blur.

**Describe the solution you'd like**
It would be great if you could add an option to specify a timeout for idle time and after that timeout expires WhatsApp web automatically gets blurred.

**Comment by deaf27577** [comment] 2023-01-30 17:28
![Screenshot_2023-01-30-20-28-07-675_com whatsapp w4b](https://user-images.githubusercontent.com/123980137/215550126-c6442e6b-e15f-4cac-b9f4-bfb43c96d6b3.jpg)





+967 778 881 434

**Comment by Sumonmiahcml78** [comment] 2024-06-06 20:15
Duplicate of #27577

**Comment by Tgentil** [comment] 2024-08-30 14:28
Feature added by #87

**Closed by Tgentil** 2024-08-30 14:28 UTC
Labels: enhancement
