### ISSUE TITLE
extention not working anymore for whatsapp

### ISSUE THREAD

**Issue by Akashsinghal261** [LukasLen/Privacy-Extension-For-WhatsApp-Web#55] opened 2024-03-04 09:27 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LukasLen** [comment] 2024-03-04 19:35
Can't reproduce this. Should be fixed with dc1799b5a12f620146b4288472f3bd0dfc088578

**Closed by LukasLen** 2024-03-04 19:35 UTC
