### ISSUE TITLE
On screen of whatsapp it unblurs everithing and isn't bluring the profile pictures

### ISSUE THREAD

**Issue by Micael-Machado** [LukasLen/Privacy-Extension-For-WhatsApp-Web#33] opened 2023-03-20 11:50 UTC
When the cursor isn't in the site but it's in the browser most part is blured but when the cursor passes to the whatsapp screen it shows everything, and it's not bluring the profile pictures.

**Comment by UsmanAhmadSaeed** [comment] 2023-03-26 01:09
@Micael-Machado can you verify that you haven't turned on this option (image below)? This might be the reason everything is unblurred when you hover on WhatsApp Web anywhere. 
As for the blurring of profile pictures, make sure you've turned on the blur profile picture option in extension settings. That maybe the reason for no blurring of profile pictures. If not, please do let me know because I've been experiencing the same issue, where profile pictures are not being blurred, and if you have the option on and are experiencing the same, it may be due to some new upgrade by WhatsApp.
Your confirmation will help @LukasLen verify if that is a persistent issue, as he'll have 2 instances where it is occurring, me and you, or otherwise it might just be me. Either case, win-win.
![image](https://user-images.githubusercontent.com/20966983/227749650-f2be183c-533f-4968-a26a-d25647413966.png)

**Comment by pragus99** [comment] 2023-03-27 02:41
@UsmanAhmadSaeed That happen to me. Blurring profile picture not working as intended. Whatsapp Web change class name for profile/group pic. Someone needs to make PR for update profilePic.css

**Comment by UsmanAhmadSaeed** [comment] 2023-03-27 06:30
@pragus99 Yeah I think that's the case. I've tried to update the class but haven't succeeded so far. I'm not sure how to find the correct class. Do you know how can I do that?

**Comment by Micael-Machado** [comment] 2023-03-27 11:47
Good morning.

 I'm using it with the settings below and the occurrence persists:

[image: image.png]

Best regards,
Micael Neto.

Em sáb., 25 de mar. de 2023 às 22:09, Usman Ahmad Saeed <
***@***.***> escreveu:

**Comment by LukasLen** [comment] 2023-03-28 09:22
Thanks for bringing this to my attention. I can confirm that the profile pictures do not blur anymore. However, the issue @Micael-Machado describes I could not replicate. Maybe you could post more info on here? Your picture wasn't uploaded to GitHub.


> Good morning. I'm using it with the settings below and the occurrence persists: [image: image.png] Best regards, Micael Neto.

**Comment by LukasLen** [comment] 2023-06-06 13:33
Fixed with 1ce7ae370633422263ae0ab033b8bc4ccd54c223

**Closed by LukasLen** 2023-06-06 13:33 UTC
